### ISSUE TITLE
Don't Reset Canvas translate after finishing

### ISSUE THREAD

**Issue by falstack** [niklasvh/html2canvas#1527]
Because the image drawn by html2canvas is not clear enough

so i do this:
```css
.canvas-container {
  width: 200%;
  height: 200%;
  transform: scale(.5);
  transform-origin: 0 0;
}
```

So I can draw a clear image

but if set this:
``` javascript
ctx.setTransform(1, 0, 0, 1, 0, 0);
```

The resulting image only accounts for a quarter of the total image
