### ISSUE TITLE
background-image height with Firefox

### ISSUE THREAD

**Issue by pedubreuil** [niklasvh/html2canvas#1599]
Hello!

I'm getting stuck with an issue about a background-image, on Firefox.
Thank you in advance for your help!
Best regards

### Bug report:

**Not working on Firefox:**

````css
div.background {
  background-image: url('./assets/images/default-background.svg');
  background-size: cover;
}
````
````css
div.background {
  background-image: url('./assets/images/default-background.svg');
  background-size: contain;
}
````
````css
div.background {
  background-image: url('./assets/images/default-background.svg');
  background-size: auto 100vh;
}
````
````css
div.background {
  background-image: url('./assets/images/default-background.svg');
  background-size: 100vw auto;
}
````

**working on Firefox:**

````css
div.background {
  background-image: url('./assets/images/default-background.svg');
  background-size: 100vw 100vh;
}
````

**Details of the error:**

Error message: `Invalid x value given for Vector`
Cause: background image height (or width) is '0'

### Specifications:

html2canvas version: "1.0.0-alpha.12"
Firefox version: 61.0.1 (64 bits)
This issue happens only with Firefox (no problem with Chrome).
