### ISSUE TITLE
Google Maps capture and tile grids...

### ISSUE THREAD

**Issue by sobomp3** [niklasvh/html2canvas#1695]
Hello all, I've seen numerous posts on trying to capture a Google Map for various purposes. In our case, we'd like to be able to print a map. We have used most of the common code suggested here to capture the map using the proper CSS transforms. However, we are almost always seeing grid lines between the tiles. Does anyone know how to fix these grid lines? Here is an example of what I'm talking about:

![image](https://user-images.githubusercontent.com/30295774/47817789-95684580-dd24-11e8-8c75-1261e16f0de9.png)

### Specifications:

 * html2canvas version tested with: 1.0.0-alpha.12
 * Browser & version: 70.0.3538.77 (and earlier versions, also Firefox, Edge)
 * Operating system: Windows 10 x64

**Comment by josiahbryan** [comment]
Same, always seeing these lines, even in the browser. Any fix?

**Comment by vlrevolution** [comment]
Experiencing the same, does anybody know anything?

**Comment by josiahbryan** [comment]
No clue, still having the same problem - never heard any response (obviously lol)

**Comment by vlrevolution** [comment]
> No clue, still having the same problem - never heard any response (obviously lol)

Try this ;)

```css
.gm-style img {
  /* Targeting only images within Google Maps */
  transform: translateZ(0) scale(1.002); /* Using scale to slightly stretch the tiles */
  backface-visibility: hidden; /* Improves rendering */
}
```
