### ISSUE TITLE
Background with background-size cover is not working.

### ISSUE THREAD

**Issue by tinganho** [niklasvh/html2canvas#288]
I have an element with 

``` css
.some-class {
  background: url('/public/images-webp/streetstyle/landingpage.webp') center center;
  background-size: cover;
}
```

CSS rule background-size: cover causes the image to not being rendered in html2canvas.
